name             'monit_test'
maintainer       'Criteo'
maintainer_email 'sre-core@criteo.com'
license          'Apache 2.0'
description      'Test cookbook for monit'
long_description 'Test cookbook for monit'
version          '0.1.0'
depends          'monit'
